services:
  - type: web
    name: acm
    runtime: go
    rootDir: acm
    buildCommand: CGO_ENABLED=1 go build -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: CGO_ENABLED
        value: "1"
